"""In-memory loader + search over the MITRE ATT&CK technique snapshot.

The snapshot at `backend/data/mitre/techniques.json` is generated by
`refresh_mitre_attack.py`. Loaded once at import time so search is
hot in-memory; refresh requires a process restart (uvicorn --reload
picks it up on next request).
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any


DATA_FILE = (
    Path(__file__).resolve().parents[3] / "data" / "mitre" / "techniques.json"
)


@lru_cache(maxsize=1)
def _load() -> list[dict[str, Any]]:
    if not DATA_FILE.exists():
        return []
    return json.loads(DATA_FILE.read_text(encoding="utf-8"))


def get_all() -> list[dict[str, Any]]:
    return list(_load())


def get_by_id(tid: str) -> dict[str, Any] | None:
    for t in _load():
        if t["id"] == tid:
            return t
    return None


def search(query: str, *, limit: int = 50) -> list[dict[str, Any]]:
    """Substring search across id + name. Results ranked:
       1. exact id match
       2. id prefix
       3. name prefix
       4. name substring
    """
    q = (query or "").strip().lower()
    if not q:
        # No query -> return first `limit` techniques (alphabetical by id).
        return _load()[:limit]

    exact: list[dict] = []
    id_prefix: list[dict] = []
    name_prefix: list[dict] = []
    name_sub: list[dict] = []

    for t in _load():
        tid = t["id"].lower()
        name = t["name"].lower()
        if tid == q:
            exact.append(t)
        elif tid.startswith(q):
            id_prefix.append(t)
        elif name.startswith(q):
            name_prefix.append(t)
        elif q in name or q in tid:
            name_sub.append(t)

    return (exact + id_prefix + name_prefix + name_sub)[:limit]
