"""add_case_number_ranges

Revision ID: 40fa49e4b0bd
Revises: a1b2c3d4e5f6
Create Date: 2026-04-08 20:52:54.286872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40fa49e4b0bd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_number_ranges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('prefix', sa.String(length=4), nullable=False),
    sa.Column('range_start', sa.Integer(), nullable=False),
    sa.Column('range_end', sa.Integer(), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_number_ranges_tenant_id'), 'case_number_ranges', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_number_ranges_tenant_id'), table_name='case_number_ranges')
    op.drop_table('case_number_ranges')
    # ### end Alembic commands ###
