"""sla_status_pause_fields

Revision ID: 7c5dad008af7
Revises: 40fa49e4b0bd
Create Date: 2026-04-09 08:27:48.464372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5dad008af7'
down_revision: Union[str, None] = '40fa49e4b0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_statuses', sa.Column('pauses_sla', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sla_records', sa.Column('status_paused_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sla_records', 'status_paused_at')
    op.drop_column('case_statuses', 'pauses_sla')
    # ### end Alembic commands ###
