"""add_is_global_to_roles

Revision ID: 8922edf5269d
Revises: 8f6d3d3294ec
Create Date: 2026-04-07 22:17:59.319621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8922edf5269d'
down_revision: Union[str, None] = '8f6d3d3294ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_global', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_global')
    # ### end Alembic commands ###
