"""classification_rubric_system

Revision ID: 95943f3f1e5b
Revises: 8922edf5269d
Create Date: 2026-04-07 23:08:53.694508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95943f3f1e5b'
down_revision: Union[str, None] = '8922edf5269d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('score1_description', sa.Text(), nullable=False),
    sa.Column('score2_description', sa.Text(), nullable=False),
    sa.Column('score3_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_thresholds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('low_max', sa.Integer(), nullable=False),
    sa.Column('medium_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_classification_thresholds_tenant')
    )
    op.add_column('case_classifications', sa.Column('scores', sa.JSON(), nullable=False))
    op.add_column('case_classifications', sa.Column('total_score', sa.Integer(), nullable=True))
    op.add_column('case_classifications', sa.Column('complexity_level', sa.String(length=10), nullable=True))
    op.drop_column('case_classifications', 'origin_detail')
    op.drop_column('case_classifications', 'urgency')
    op.drop_column('case_classifications', 'complexity_detail')
    op.drop_column('case_classifications', 'area')
    op.drop_column('case_classifications', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_classifications', sa.Column('category', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('case_classifications', sa.Column('area', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('case_classifications', sa.Column('complexity_detail', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('case_classifications', sa.Column('urgency', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('case_classifications', sa.Column('origin_detail', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('case_classifications', 'complexity_level')
    op.drop_column('case_classifications', 'total_score')
    op.drop_column('case_classifications', 'scores')
    op.drop_table('classification_thresholds')
    op.drop_table('classification_criteria')
    # ### end Alembic commands ###
